package ca.utoronto.utm.tabPanel;

import javafx.scene.shape.Rectangle;
import javafx.scene.shape.Shape;

import ca.utoronto.utm.paint.View;
import javafx.event.ActionEvent;
import javafx.event.EventHandler;
import javafx.scene.Node;
import javafx.scene.control.Button;
import javafx.scene.control.TitledPane;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.input.MouseEvent;
import javafx.scene.layout.GridPane;
import javafx.scene.layout.HBox;
import javafx.scene.paint.Color;

/** Used to pass a color a color to a ColorAccordion's mouse
 * clicker event handler. Also sets a grid of colors
 * in a grid pane as well as adding a button for a
 * transparent color setting.
*/
public class ColorGrid extends TitledPane implements EventHandler<ActionEvent>{
	private GridPane gridPane = new GridPane();
	private Color color = Color.BLACK;
	private Button clear;
	public View view;
	public String type;
	private ColorAccordions parent;
	private Rectangle currColor;
	
	/** Constructor for ColorGrid. Creates the grid pane for colors
	 * and a button that sets the color to transparent.
	 * 
	 * @param view Used to Access controller
	 * @param name Determines Name for Color being set.
	 * @param parent Color grid container
	 */
	public ColorGrid(View view, String name,ColorAccordions parent){
		this.clear = new Button("Empty");
		this.clear.setOnAction(this);
		this.clear.setMaxWidth(100);
		this.view = view;
		this.type=name;
		this.parent=parent;
		Image currentImage = null;
		this.setGraphic(this.configureNode());
		
		int col = 0;
		int row = 0;
		for(int hue = 0; hue <=270; hue+=18)
		{
			this.color = Color.hsb(hue, 1.0, 1.0, 1.0);
			Rectangle rect = new Rectangle(0, 0, 26, 20);
			rect.setFill(this.color);
			this.gridPane.add(rect, col, row);
			row ++;
			if(row == 6) {
				row = 0;
				col ++;
			}
		}
		Rectangle rect = new Rectangle(0, 0, 26, 20);
		this.color = Color.hsb(0, 0, 0, 1.0);
		rect.setFill(this.color);
		this.gridPane.add(rect, col, row);
		rect = new Rectangle(0, 0, 26, 20);
		this.color = Color.hsb(270, 0, 1.0, 1.0);
		rect.setFill(this.color);
		this.gridPane.add(rect, col, row+1);
		for (Node node : gridPane.getChildren()) {
			node.setOnMouseClicked(e -> handleMouseClick(e));
		}
		this.gridPane.add(this.clear, 0, row+2,3,1);
		this.setContent(gridPane);
	}
	
	/** MouseEvent Handler. Handles action for each cell of
	 * the color grid pane to change the the set color
	 * to the grid pane cell's color.
	 * 
	 * @param e MouseEvent generated by User Input.
	 */
	private void handleMouseClick (MouseEvent e) {
		Node source = (Node)e.getSource() ;
        Integer colIndex = GridPane.getColumnIndex(source);
        Integer rowIndex = GridPane.getRowIndex(source);
        for (Node node : gridPane.getChildren()) {
            if (GridPane.getColumnIndex(node) == colIndex && GridPane.getRowIndex(node) == rowIndex) {
            	this.color = (Color) ((Shape) node).getFill();
            }
        }
        this.currColor.setFill(this.color);
        if (this.type=="Fill") {
        	this.parent.handleMouseClickF(this);
        } else {
        	this.parent.handleMouseClickB(this);
        }
    }
	
	/** Returns Currently Stored Color.
	 * 
	 * @return selected color
	 */
	public Color getColor() {
		return this.color;
	}
	/** Handler for the Empty button to set transparent.
	 * 
	 * @param ActionEvent event for when the Empty button is clicked.
	 */
	@Override
	public void handle(ActionEvent event) {
		this.color = Color.TRANSPARENT;
		this.currColor.setFill(Color.TRANSPARENT);
		if (this.type=="Fill") {
        	this.parent.handleMouseClickF(this);
        } else {
        	this.parent.handleMouseClickB(this);
        }
	}
	/** Changes the color of the accordion icon to reflect the current
	 * selected color.
	 * 
	 * @return HBox holding the icon that represents the currently selected color.
	 */
	private HBox configureNode() {
		HBox out = new HBox(10);
		Image currentImage = null;
		this.currColor = new Rectangle(0,0,20,20);
		this.currColor.setStroke(Color.BLACK);
		if(this.type=="Border") {
			currentImage = new Image("resources/borderColor.png",20,20,true,true);
		}
		if(this.type=="Fill") {
			currentImage = new Image("resources/fillColor.png",20,20,true,true);
			this.currColor.setFill(Color.TRANSPARENT);
		}
		out.getChildren().add(new ImageView(currentImage));
		out.getChildren().add(this.currColor);
		return out;
	}
}
